const projectData = [
  {
    image: './req/1.png',
    projectname: 'Fast Lane Racers',
    field: 'Full-Stack-Project',
    technologies: ['bxl-html5', 'bxl-css3', 'bxl-javascript', 'bxl-react', 'bxl-postgresql'],
    description: 'Full stack app for Swift car booking, reserve rides by date and city for dependable travel experiences.',
    livelink: 'https://shiny-longma-bba6fb.netlify.app/cars',
    sourcelink: 'https://github.com/muneeb3123/Fast-Lane-Racers-front-end',
  },
  {
    image: './req/Weather.png',
    projectname: 'Weather360',
    field: 'React-Redux-Project',
    technologies: ['bxl-html5', 'bxl-css3', 'bxl-javascript', 'bxl-react',  'bxl-redux'],
    description: 'Weather360 is a robust web application that offers precise weather information for cities worldwide',
    livelink: 'https://shimmering-heliotrope-f0efd9.netlify.app/',
    sourcelink: 'https://github.com/muneeb3123/weather-app',
  },
  {
    image: './req/space-traveller.png',
    projectname: 'Space Traveller',
    field: 'React-Redux-Project',
    technologies: ['bxl-html5', 'bxl-css3', 'bxl-javascript', 'bxl-react',  'bxl-redux'],
    description: 'React and Redux web app utilizing SpaceX API for rocket and mission info, reservations, and profiles.',
    livelink: 'https://melodic-alpaca-4e8a79.netlify.app/rockets',
    sourcelink: 'https://github.com/muneeb3123/space-traveller',
  },
  {
    image: './req/Calculator.png',
    projectname: 'Math Magician',
    field: 'React-Redux-Project',
    technologies: ['bxl-html5', 'bxl-css3', 'bxl-javascript', 'bxl-react', 'bxl-redux'],
    description: 'A versatile calculator app for efficient math operations with welcoming and calculator web pages.',
    livelink: 'https://cosmic-marigold-cfd2d9.netlify.app/calculator',
    sourcelink: 'https://github.com/muneeb3123/math-magician',
  },
  {
    image: './req/Capstone.png',
    projectname: 'Fast Lane Racers',
    field: 'JavaScript-Project',
    technologies: ['bxl-html5', 'bxl-css3', 'bxl-javascript'],
    description: 'FilmFussion: Web hub for TV and movies with user ratings, reviews, and interactive community features.',
    livelink: 'https://film-fusion-movie-hub.netlify.app/',
    sourcelink: 'https://github.com/muneeb3123/capstone-javascript',
  },
  {
    image: './req/Bookstore.png',
    projectname: 'Bookstore CMS',
    field: 'React-Project',
    technologies: ['bxl-html5', 'bxl-css3', 'bxl-javascript', 'bxl-react'],
    description: 'A React web app for managing book collections, enabling users to view and control their books.',
    livelink: 'https://effortless-haupia-07a915.netlify.app/',
    sourcelink: 'https://github.com/muneeb3123/react-bookstore',
  },
];
export default projectData;
