const projectData = [
  {
    snapshot: 'req/Weather.png',
    projectname: 'Weather360',
    technologies: ['HTML', 'CSS', 'JAVASCRIPT', 'Github', 'Ruby', 'Bootstrap'],
    dot: 'req/dot.png',
    para: 'Welcome to Weather360, a robust web application that offers precise weather information for cities worldwide. Weather360 enables you to effortlessly access up-to-date weather conditions, forecasts, and other pertinent details for any location across the globe. This document will walk you through the installation procedure and present an outline of the applications existing features, along with some thrilling future enhancements.',
    frame: ['Muneeb', 'Back End Dev', '2015'],
    smBtnText: 'See Project',
    popimage: 'req/Weather.png',
    disdes: `Welcome to Weather360, a robust web application that offers precise weather information for cities worldwide. Weather360 enables you to effortlessly access up-to-date weather conditions, forecasts, and other pertinent details for any location across the globe. This document will walk you through the installation procedure and present an outline of the application's existing features, along with some thrilling future enhancements.`,
    sep: 'req/sep.png',
    livelogo: 'req/live-icon.svg',
    sourcelogo: 'req/github-blue.svg',
    livelink: 'https://shimmering-heliotrope-f0efd9.netlify.app/',
    sourcelink: 'https://github.com/muneeb3123/weather-app',
  },
  {
    snapshot: 'req/Bookstore.png',
    projectname: 'Bookstore',
    technologies: ['HTML', 'CSS', 'JAVASCRIPT', 'Github', 'Ruby', 'Bootstrap'],
    dot: 'req/dot.png',
    para: 'The Bookstore project is a web application built using React. It provides the foundation for a Bookstore website, allowing users to view and manage a collection of books. The project utilizes React Router V6 for client-side routing.',
    frame: ['CANOPY', 'Back End Dev', '2015'],
    smBtnText: 'See Project',
    popimage: 'req/Bookstore.png',
    disdes: `The Bookstore project is a web application built using React. It provides the foundation for a Bookstore website, allowing users to view and manage a collection of books. The project utilizes React Router V6 for client-side routing.`,
    sep: 'req/sep.png',
    livelogo: 'req/live-icon.svg',
    sourcelogo: 'req/github-blue.svg',
    livelink: 'https://effortless-haupia-07a915.netlify.app',
    sourcelink: 'https://github.com/muneeb3123/react-bookstore',
  },
  {
    snapshot: 'req/Capstone.png',
    projectname: 'Movie fusion',
    technologies: ['HTML', 'CSS', 'JAVASCRIPT', 'Github', 'Ruby', 'Bootstrap'],
    dot: 'req/dot.png',
    para: 'FilmFussion is a web-based platform that provides a comprehensive database of TV shows and movies. The website allows users to rate and comment on movies, share their opinions and recommendations, and interact with other members of the community.',
    frame: ['CANOPY', 'Back End Dev', '2015'],
    smBtnText: 'See Project',
    popimage: 'req/Capstone.png',
    disdes: `FilmFussion is a web-based platform that provides a comprehensive database of TV shows and movies. The website allows users to rate and comment on movies, share their opinions and recommendations, and interact with other members of the community.`,
    sep: 'req/sep.png',
    livelogo: 'req/live-icon.svg',
    sourcelogo: 'req/github-blue.svg',
    livelink: 'https://gregarious-malasada-255b5d.netlify.app',
    sourcelink: 'https://github.com/muneeb3123/capstone-javascript',
  },
  {
    snapshot: 'req/Calculator.png',
    projectname: 'Calculator',
    technologies: ['HTML', 'CSS', 'JAVASCRIPT', 'Github', 'Ruby', 'Bootstrap'],
    dot: 'req/dot.png',
    para: 'In this project i will create a calculator which perform mathematics operations.A website with three dynamic pages. The home page extends a warm welcome, the calculator page empowers you to perform arithmetic operations effortlessly, and the quote page fetches random quotes using React and React Router. Experience the convenience of math calculations and immerse yourself in a world of inspiration.',
    frame: ['CANOPY', 'Back End Dev', '2015'],
    smBtnText: 'See Project',
    popimage: 'req/Calculator.png',
    disdes: `In this project i will create a calculator which perform mathematics operations.A website with three dynamic pages. The home page extends a warm welcome, the calculator page empowers you to perform arithmetic operations effortlessly, and the quote page fetches random quotes using React and React Router. Experience the convenience of math calculations and immerse yourself in a world of inspiration.`,
    sep: 'req/sep.png',
    livelogo: 'req/live-icon.svg',
    sourcelogo: 'req/github-blue.svg',
    livelink: 'https://cosmic-marigold-cfd2d9.netlify.app/',
    sourcelink: 'https://github.com/muneeb3123/math-magician',
  },
];
export default projectData;
